/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cgpi;

/**
 *
 * @author student
 */
public class cgpi extends javax.swing.JFrame {

/**
 * Creates new form cgpi
 */
public cgpi() {
        initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        eimpane = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        enas_int = new javax.swing.JTextField();
        enas_term = new javax.swing.JTextField();
        enas_sem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        error_enas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        am_int = new javax.swing.JTextField();
        am_sem = new javax.swing.JTextField();
        am_term = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        error_am = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        oopm_term = new javax.swing.JTextField();
        oopm_pracs = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        error_oopm = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        edc_int = new javax.swing.JTextField();
        edc_term = new javax.swing.JTextField();
        edc_pracs = new javax.swing.JTextField();
        edc_sem = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        error_edc = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        eim_int = new javax.swing.JTextField();
        eim_sem = new javax.swing.JTextField();
        error_eim = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dcd_int = new javax.swing.JTextField();
        dcd_term = new javax.swing.JTextField();
        dcd_pracs = new javax.swing.JTextField();
        dcd_sem = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        error_dcd = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE)
                );
        jDialog1Layout.setVerticalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 300, Short.MAX_VALUE)
                );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel8.setText("INTERNAL");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel9.setText("TERM WORK");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel10.setText("END SEMESTER");

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jButton1.setText("NEXT>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

        error_enas.setForeground(new java.awt.Color(255, 0, 51));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("ENAS");

        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("Please enter numbers only.");

        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("Please enter numbers only.");

        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("Please enter numbers only.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                          .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                              .addGap(88, 88, 88)
                                              .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                  .addComponent(jLabel8)
                                                                  .addGap(76, 76, 76)
                                                                  .addComponent(enas_int, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                  .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(jLabel9)
                                                                            .addComponent(jLabel10))
                                                                  .addGap(51, 51, 51)
                                                                  .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                            .addComponent(enas_term, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                                                            .addComponent(enas_sem)))
                                                        .addComponent(jLabel26)
                                                        .addComponent(jLabel28)
                                                        .addComponent(jLabel27)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                              .addGap(166, 166, 166)
                                              .addComponent(jLabel7))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                        .addGap(50, 50, 50)
                                                        .addComponent(error_enas, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                        .addGap(147, 147, 147)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                              .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                          .addContainerGap(31, Short.MAX_VALUE))
                );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                          .addContainerGap()
                          .addComponent(jLabel7)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(error_enas, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(enas_int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel26)
                          .addGap(10, 10, 10)
                          .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(enas_term, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel27)
                          .addGap(18, 18, 18)
                          .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(enas_sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addGap(5, 5, 5)
                          .addComponent(jLabel28)
                          .addGap(18, 18, 18)
                          .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addContainerGap(38, Short.MAX_VALUE))
                );

        eimpane.addTab("ENAS", jPanel4);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel1.setText("INTERNAL");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel2.setText("TERM WORK");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel3.setText("END SEMESTER");

        am_int.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                am_intActionPerformed(evt);
                        }
                });

        am_term.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                am_termActionPerformed(evt);
                        }
                });

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jButton6.setText("NEXT>>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton6ActionPerformed(evt);
                        }
                });

        error_am.setForeground(new java.awt.Color(255, 0, 102));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("AM-III");

        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("Please enter numbers only.");

        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("Please enter numbers only.");

        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("Please enter numbers only.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                          .addGap(0, 74, Short.MAX_VALUE)
                          .addComponent(jLabel30)
                          .addGap(190, 190, 190))
                .addGroup(jPanel1Layout.createSequentialGroup()
                          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                              .addComponent(error_am, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                  .addGap(142, 142, 142)
                                                                  .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                  .addGap(71, 71, 71)
                                                                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(jLabel31)
                                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                      .addGap(57, 57, 57)
                                                                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                .addComponent(am_int)
                                                                                                .addComponent(am_term)
                                                                                                .addComponent(am_sem, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                                                                            .addComponent(jLabel29)
                                                                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                              .addGap(156, 156, 156)
                                              .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                          .addContainerGap()
                          .addComponent(jLabel21)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(error_am, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(am_int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel31)
                          .addGap(1, 1, 1)
                          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(am_term, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addGap(5, 5, 5)
                          .addComponent(jLabel30)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(am_sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel29)
                          .addGap(31, 31, 31)
                          .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addContainerGap(45, Short.MAX_VALUE))
                );

        eimpane.addTab("AM-III", jPanel1);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel4.setText("TERM WORK");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel5.setText("PRACTICAL");

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jButton4.setText("NEXT>>");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                        }
                });

        error_oopm.setForeground(new java.awt.Color(255, 0, 51));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("OOPM");

        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("Please enter numbers only.");

        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setText("Please enter numbers only.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                          .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                              .addGap(80, 80, 80)
                                              .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                  .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(jLabel5))
                                                                  .addGap(39, 39, 39)
                                                                  .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(oopm_pracs, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(oopm_term, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jLabel33)
                                                        .addComponent(jLabel32)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                              .addGap(150, 150, 150)
                                              .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                              .addGap(159, 159, 159)
                                              .addComponent(jLabel22))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                              .addGap(46, 46, 46)
                                              .addComponent(error_oopm, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                          .addContainerGap(68, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                          .addGap(0, 0, Short.MAX_VALUE)
                          .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                          .addContainerGap()
                          .addComponent(jLabel22)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(error_oopm, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(oopm_term, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addGap(3, 3, 3)
                          .addComponent(jLabel33)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(oopm_pracs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel32)
                          .addGap(32, 32, 32)
                          .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addGap(18, 18, 18)
                          .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addContainerGap(73, Short.MAX_VALUE))
                );

        eimpane.addTab("OOPM", jPanel6);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel15.setText("INTERNAL");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel16.setText("TERM WORK");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel17.setText("PRACTICAL");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel18.setText("END SEMESTER");

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jButton2.setText("NEXT>>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

        error_edc.setForeground(new java.awt.Color(255, 0, 51));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("EDC-I");

        jLabel34.setForeground(new java.awt.Color(255, 0, 0));
        jLabel34.setText("Please enter numbers only.");

        jLabel35.setForeground(new java.awt.Color(255, 0, 0));
        jLabel35.setText("Please enter numbers only.");

        jLabel36.setForeground(new java.awt.Color(255, 0, 0));
        jLabel36.setText("Please enter numbers only.");

        jLabel37.setForeground(new java.awt.Color(255, 0, 0));
        jLabel37.setText("Please enter numbers only.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                              .addGap(67, 67, 67)
                                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(error_edc, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                      .addComponent(jLabel18)
                                                                                      .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                      .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                      .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING))
                                                                            .addComponent(jLabel35)
                                                                            .addComponent(jLabel37))
                                                                  .addGap(14, 14, 14)
                                                                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(edc_int, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(edc_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(edc_pracs, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(edc_term, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jLabel34)
                                                        .addComponent(jLabel36)
                                                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                              .addGap(104, 104, 104)
                                              .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                              .addGap(154, 154, 154)
                                              .addComponent(jLabel23)))
                          .addContainerGap(69, Short.MAX_VALUE))
                );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                          .addContainerGap()
                          .addComponent(jLabel23)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(error_edc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(edc_int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel34)
                          .addGap(4, 4, 4)
                          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel16)
                                                        .addComponent(edc_term, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                              .addGap(7, 7, 7)
                                              .addComponent(jLabel35)
                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                              .addComponent(jLabel17))
                                    .addComponent(edc_pracs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addGap(4, 4, 4)
                          .addComponent(jLabel36)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(edc_sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel37)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                          .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addGap(6, 6, 6))
                );

        eimpane.addTab("EDC-I", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jButton3.setText("NEXT>>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel19.setText("INTERNAL");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel20.setText("END SEMESTER");

        eim_int.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                eim_intActionPerformed(evt);
                        }
                });

        eim_sem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                eim_semActionPerformed(evt);
                        }
                });

        error_eim.setForeground(new java.awt.Color(255, 0, 51));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("EIM");

        jLabel38.setForeground(new java.awt.Color(255, 0, 0));
        jLabel38.setText("Please enter numbers only.");

        jLabel39.setForeground(new java.awt.Color(255, 0, 0));
        jLabel39.setText("Please enter numbers only.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                          .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                              .addGap(70, 70, 70)
                                              .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                                                  .addGap(144, 144, 144)
                                                                  .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(eim_int, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(eim_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(error_eim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                              .addGap(118, 118, 118)
                                              .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                              .addGap(160, 160, 160)
                                              .addComponent(jLabel24)))
                          .addContainerGap(70, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                          .addGap(0, 0, Short.MAX_VALUE)
                          .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39))
                          .addGap(199, 199, 199))
                );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                          .addContainerGap(30, Short.MAX_VALUE)
                          .addComponent(jLabel24)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addComponent(error_eim, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(eim_int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel39)
                          .addGap(18, 18, 18)
                          .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(eim_sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel38)
                          .addGap(61, 61, 61)
                          .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addGap(19, 19, 19))
                );

        eimpane.addTab("EIM", jPanel5);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel11.setText("INTERNAL");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel12.setText("END SEMESTER");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel13.setText("TERM WORK");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel14.setText("PRACTICAL");

        dcd_int.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                dcd_intActionPerformed(evt);
                        }
                });

        dcd_term.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                dcd_termActionPerformed(evt);
                        }
                });

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jButton5.setText("SUBMIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                        }
                });

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setText("  DCD   ");

        jLabel40.setForeground(new java.awt.Color(255, 0, 0));
        jLabel40.setText("Please enter numbers only.");

        jLabel41.setForeground(new java.awt.Color(255, 0, 0));
        jLabel41.setText("Please enter numbers only.");

        jLabel42.setForeground(new java.awt.Color(255, 0, 0));
        jLabel42.setText("Please enter numbers only.");

        jLabel43.setForeground(new java.awt.Color(255, 0, 0));
        jLabel43.setText("Please enter numbers only.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                              .addGap(144, 144, 144)
                                              .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                              .addGap(161, 161, 161)
                                              .addComponent(jLabel25)))
                          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                          .addGap(46, 46, 46)
                          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                              .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(jLabel13)
                                                                            .addComponent(jLabel11)
                                                                            .addComponent(jLabel14)
                                                                            .addComponent(jLabel12))
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(dcd_int, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(dcd_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(dcd_pracs, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(dcd_term, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                                  .addGap(40, 40, 40)
                                                                  .addComponent(error_dcd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                  .addGap(0, 0, Short.MAX_VALUE)
                                                                  .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                              .addGap(94, 94, 94))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                              .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel41)
                                                        .addComponent(jLabel40)
                                                        .addComponent(jLabel42)
                                                        .addComponent(jLabel43))
                                              .addGap(0, 0, Short.MAX_VALUE))))
                );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                          .addContainerGap()
                          .addComponent(jLabel25)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(error_dcd)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dcd_int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel43)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dcd_term, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addGap(2, 2, 2)
                          .addComponent(jLabel42)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dcd_pracs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                          .addGap(1, 1, 1)
                          .addComponent(jLabel40)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dcd_sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel41)
                          .addGap(3, 3, 3)
                          .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addGap(17, 17, 17))
                );

        eimpane.addTab("DCD", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(eimpane, javax.swing.GroupLayout.Alignment.TRAILING)
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(eimpane)
                );

        pack();
}    // </editor-fold>//GEN-END:initComponents

private void am_termActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_am_termActionPerformed
        // TODO add your handling code here:
}    //GEN-LAST:event_am_termActionPerformed

private void am_intActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_am_intActionPerformed
        // TODO add your handling code here:
}    //GEN-LAST:event_am_intActionPerformed

private void dcd_termActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_dcd_termActionPerformed
        // TODO add your handling code here:
}    //GEN-LAST:event_dcd_termActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_jButton1ActionPerformed
        int flag=0; int flag1=0; int flag2=0; int flag3=0;
        String sErr="Invalid Entries in ";
        try
        {
                int Enas_int=enas_int.getText().length()==0 ? 0 : Integer.parseInt(enas_int.getText());
                //jLabel45.setText(Integer.toString(Enas_int));
                if(Enas_int>20)
                {
                        sErr=sErr+ " "+ "internals";
                        flag1=1;
                }
                else
                {flag1=0;}
                int Enas_term=enas_term.getText().length()==0 ? 0 : Integer.parseInt(enas_term.getText());
                if(Enas_term>25)
                {
                        sErr=sErr+ " " + "termwork";
                        flag2=1;
                }
                else
                {flag2=0;}
                int Enas_sem=enas_sem.getText().length()==0 ? 0 : Integer.parseInt(enas_sem.getText());
                if(Enas_sem > 80)
                {
                        sErr=sErr+" "+"semester";
                        flag3=1;
                }
                else
                { flag3=0;}

                if(enas_int.getText().isEmpty())
                {
                        enas_int.grabFocus();
                        flag1=1;
                }
                else if(enas_term.getText().isEmpty())
                {
                        enas_term.grabFocus();
                        flag2=1;
                }
                else if(enas_sem.getText().isEmpty())
                {
                        enas_sem.grabFocus();
                        flag3=1;
                }
                // else{ flag=0;}
                if(flag1==0&&flag2==0&&flag3==0) {
                        jLabel44.setText(" ");
                }
                else
                {
                        jLabel44.setText(sErr);
                }
        }catch(NumberFormatException e)
        {
                flag=1;
        }
        if(flag1==0&&flag2==0&&flag3==0&&flag==0)
                eimpane.setSelectedIndex(1);
        else
        {
                error_enas.setText("Please enter numbers only"); // TODO add your handling code here:
        }
}    //GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_jButton2ActionPerformed
        int flag=0; int flag1=0; int flag2=0; int flag3=0; int flag4=0;
        String sErr="Invalid Entries in ";
        try
        {
                int Edc_int=edc_int.getText().length()==0 ? 0 : Integer.parseInt(edc_int.getText());
                if(Edc_int>20)
                {
                        sErr=sErr+ " "+ "internals";
                        flag1=1;
                }
                else
                {flag1=0;}
                int Edc_term=edc_term.getText().length()==0 ? 0 : Integer.parseInt(edc_term.getText());
                if(Edc_term>25)
                {
                        sErr=sErr+ " " + "termwork";
                        flag2=1;
                }
                else
                {flag2=0;}
                int Edc_pracs=edc_pracs.getText().length()==0 ? 0 : Integer.parseInt(edc_pracs.getText());
                if(Edc_pracs>25)
                {
                        sErr=sErr+ " " + "practical";
                        flag3=1;
                }
                else
                {flag3=0;}
                int Edc_sem=edc_sem.getText().length()==0 ? 0 : Integer.parseInt(edc_sem.getText());
                if(Edc_sem > 80)
                {
                        sErr=sErr+" "+"semester";
                        flag4=1;
                }
                else
                { flag4=0;}
                if(edc_int.getText().isEmpty())
                {
                        edc_int.grabFocus();
                        flag1=1;
                }
                else if(edc_term.getText().isEmpty())
                {
                        edc_term.grabFocus();
                        flag2=1;
                }
                else if(edc_pracs.getText().isEmpty())
                {
                        edc_term.grabFocus();
                        flag3=1;
                }
                else if(edc_sem.getText().isEmpty())
                {
                        edc_sem.grabFocus();
                        flag4=1;
                }
                // else{ flag=0;}
                if(flag1==0&&flag2==0&&flag3==0&&flag4==0) {
                        jLabel49.setText(" ");
                }
                else
                {
                        jLabel49.setText(sErr);
                }
        }catch(NumberFormatException e)
        {
                flag=1;
        }
        if(flag==0&&flag1==0&&flag2==0&&flag3==0&&flag4==0)
                eimpane.setSelectedIndex(4);
        else
        {
                error_edc.setText("Please enter numbers only"); // TODO add your handling code here:
        }                       // TODO add your handling code here:
}    //GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_jButton3ActionPerformed
        int flag=0; int flag1=0; int flag2=0;
        String sErr="Invalid Entries in ";
        try
        {
                int Eim_int=eim_int.getText().length()==0 ? 0 : Integer.parseInt(eim_int.getText());
                if(Eim_int>20)
                {
                        sErr=sErr+ " " + "internals";
                        flag1=1;
                }
                else
                {flag1=0;}
                int Eim_sem=eim_sem.getText().length()==0 ? 0 : Integer.parseInt(eim_sem.getText());
                if(Eim_sem > 80)
                {
                        sErr=sErr+ " " + "semester";
                        flag2=1;
                }
                else
                { flag2=0;}
                if(eim_int.getText().isEmpty())
                {
                        eim_int.grabFocus();
                        flag1=1;
                }
                else if(eim_sem.getText().isEmpty())
                {
                        enas_sem.grabFocus();
                        flag2=1;
                }
                // else{ flag=0;}
                if(flag1==0&&flag2==0) {
                        jLabel48.setText(" ");
                }
                else
                {
                        jLabel48.setText(sErr);
                }
        }catch(NumberFormatException e)
        {
                flag=1;
        }
        if(flag==0&&flag1==0&&flag2==0)
                eimpane.setSelectedIndex(5);
        else
        {
                error_eim.setText("Please enter numbers only"); // TODO add your handling code here:
        }
        // TODO add your handling code here:
}    //GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_jButton4ActionPerformed
        int flag=0; int flag1=0; int flag2=0;
        String sErr="Invalid Entries in ";
        try
        {
                int Oopm_term=oopm_term.getText().length()==0 ? 0 : Integer.parseInt(oopm_term.getText());
                if(Oopm_term>25)
                {
                        sErr=sErr + " " + "termwork";
                        flag1=1;
                }
                else
                {flag1=0;}
                int Oopm_pracs=oopm_pracs.getText().length()==0 ? 0 : Integer.parseInt(oopm_pracs.getText());
                if(Oopm_pracs > 25)
                {
                        sErr=sErr + " " + "practicals";
                        flag2=1;
                }
                else
                { flag2=0;}
                if(oopm_pracs.getText().isEmpty())
                {
                        oopm_pracs.grabFocus();
                        flag1=1;
                }
                else if(oopm_term.getText().isEmpty())
                {
                        oopm_term.grabFocus();
                        flag2=1;
                }
                // else{ flag=0;}
                if(flag1==0&&flag2==0) {
                        jLabel50.setText(" ");// entry done right in the first go itself.
                }
                else
                {
                        jLabel50.setText(sErr);
                }
        }catch(NumberFormatException e)
        {
                flag=1;
        }
        if(flag==0 && flag1==0 && flag2==0)
                eimpane.setSelectedIndex(3);
        else
        {
                error_oopm.setText("Please enter numbers only"); // TODO add your handling code here:
        }
}    //GEN-LAST:event_jButton4ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_jButton6ActionPerformed
        int flag=0; int flag1=0; int flag2=0; int flag3=0;
        String sErr="Invalid Entries in ";
        try
        {
                int Am_int=am_int.getText().length()==0 ? 0 : Integer.parseInt(am_int.getText());
                //jLabel45.setText(Integer.toString(Enas_int));
                if(Am_int>20)
                {
                        sErr=sErr+ " "+ "internals";
                        flag1=1;
                }
                else
                {flag1=0;}
                int Am_term=am_term.getText().length()==0 ? 0 : Integer.parseInt(am_term.getText());
                if(Am_term>25)
                {
                        sErr=sErr+ " " + "termwork";
                        flag2=1;
                }
                else
                {flag2=0;}
                int Am_sem=am_sem.getText().length()==0 ? 0 : Integer.parseInt(am_sem.getText());
                if(Am_sem > 80)
                {
                        sErr=sErr+" "+"semester";
                        flag3=1;
                }
                else
                { flag3=0;}
                if(am_int.getText().isEmpty())
                {
                        am_int.grabFocus();
                        flag1=1;
                }
                else if(am_term.getText().isEmpty())
                {
                        am_term.grabFocus();
                        flag2=1;
                }
                else if(am_sem.getText().isEmpty())
                {
                        am_sem.grabFocus();
                        flag3=1;
                }
                // else{ flag=0;}
                if(flag1==0&&flag2==0&&flag3==0) {
                        jLabel46.setText(" ");
                }
                else
                {
                        jLabel46.setText(sErr);
                }
        }catch(NumberFormatException e)
        {
                flag=1;
        }
        if(flag==0&&flag1==0&&flag2==0&&flag3==0)
                eimpane.setSelectedIndex(2);
        else
        {
                error_am.setText("Please enter numbers only"); // TODO add your handling code here:
        }
}    //GEN-LAST:event_jButton6ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_jButton5ActionPerformed
        int flag=0; int flag1=0; int flag2=0; int flag3=0; int flag4=0;

        String sErr="Invalid Entries in ";
        try
        {
                int Dcd_int=dcd_int.getText().length()==0 ? 0 : Integer.parseInt(dcd_int.getText());
                //jLabel45.setText(Integer.toString(Enas_int));
                if(Dcd_int>20)
                {
                        sErr=sErr+ " "+ "internals";
                        flag1=1;
                }
                else
                {flag1=0;}
                int Dcd_term=dcd_term.getText().length()==0 ? 0 : Integer.parseInt(dcd_term.getText());
                if(Dcd_term>25)
                {
                        sErr=sErr+ " " + "termwork";
                        flag2=1;
                }
                else
                {flag2=0;}
                int Dcd_pracs=dcd_pracs.getText().length()==0 ? 0 : Integer.parseInt(dcd_pracs.getText());
                if(Dcd_pracs>25)
                {
                        sErr=sErr+ " " + "termwork";
                        flag3=1;
                }
                else
                {flag3=0;}
                int Dcd_sem=dcd_sem.getText().length()==0 ? 0 : Integer.parseInt(dcd_sem.getText());
                if(Dcd_sem > 80)
                {
                        sErr=sErr+" "+"semester";
                        flag4=1;
                }
                else
                { flag4=0;}

                if(dcd_int.getText().isEmpty())
                {
                        dcd_int.grabFocus();
                        flag1=1;
                }
                else if(dcd_term.getText().isEmpty())
                {
                        dcd_term.grabFocus();
                        flag2=1;
                }
                else if(dcd_pracs.getText().isEmpty())
                {
                        dcd_pracs.grabFocus();
                        flag3=1;
                }
                else if(dcd_sem.getText().isEmpty())
                {
                        dcd_sem.grabFocus();
                        flag4=1;
                }
                // else{ flag=0;}
                if(flag1==0&&flag2==0&&flag3==0&&flag4==0) {
                        jLabel47.setText(" ");
                }
                else
                {
                        jLabel47.setText(sErr);
                }
        }catch(NumberFormatException e)
        {
                flag=1;
        }
        if(flag==0&&flag1==0&&flag2==0&&flag3==0&&flag4==0) {
                //error_dcd.setText(Double.toString(calculate()[0]));
                display obj=new display();
                obj.setVisible(true);
                this.setVisible(false);
                if(calculate()[0]<=4)
                {
                        obj.jLabel2.setText("Unsuccessful");
                        obj.display_msg.setText((Double.toString(calculate()[0])));
                }
                else
                {
                        obj.jLabel2.setText("successful");
                        obj.display_msg.setText((Double.toString(calculate()[0])));
                }
                //(Double.toString(calculate()[0]));
                // TODO add your handling code here:
        } else
        {
                error_dcd.setText("Please enter numbers only"); // TODO add your handling code here:
        }
}    //GEN-LAST:event_jButton5ActionPerformed

double[] calculate()
{
        double r1=0.0;
        double[] R=new double[2];
        double Edc_term=Double.parseDouble(edc_term.getText());
        double Edc_sem=Double.parseDouble(edc_sem.getText());
        double Edc_int=Double.parseDouble(edc_int.getText());
        double Edc_pracs=Double.parseDouble(edc_pracs.getText());
        if(Edc_term>=10)
        {
                if(Edc_int<8)
                {
                        if(Edc_sem>=40)
                        {
                                r1=1.0;
                        }
                }
                else
                {
                        if(Edc_sem>=24 && Edc_pracs>=10)
                        {
                                r1=1.0;
                        }
                }
        }
        double r2=0.0;
        double Dcd_term=Double.parseDouble(dcd_term.getText());
        double Dcd_sem=Double.parseDouble(dcd_sem.getText());
        double Dcd_int=Double.parseDouble(dcd_int.getText());
        double Dcd_pracs=Double.parseDouble(dcd_pracs.getText());
        if(Dcd_term>=10)
        {
                if(Dcd_int<8)
                {
                        if(Dcd_sem>=40)
                        {
                                r2=1.0;
                        }
                }
                else
                {
                        if(Dcd_sem>=24 && Dcd_pracs>=10)
                        {
                                r2=1.0;
                        }
                }
        }
        double r3=0.0;
        double Oopm_term=Double.parseDouble(oopm_term.getText());
        double Oopm_pracs=Double.parseDouble(oopm_pracs.getText());
        if(Oopm_term>=10 && Oopm_pracs>=10)
        {
                r3=1.0;
        }
        double r4=0.0;
        double Eim_int=Double.parseDouble(eim_int.getText());
        double Eim_sem=Double.parseDouble(eim_sem.getText());
        if(Eim_int<8)
        {
                if(Eim_sem>=40)
                {
                        r4=1.0;
                }
        }
        double r5=0.0;
        double Enas_int=Double.parseDouble(enas_int.getText());
        double Enas_term=Double.parseDouble(enas_term.getText());
        double Enas_sem=Double.parseDouble(enas_sem.getText());
        if(Enas_term>=10)
        {
                if(Enas_int<8)
                {
                        if(Enas_sem>=40)
                        {
                                r5=1.0;
                        }
                }
                else
                {
                        if(Enas_sem>=24)
                        {
                                r5=1.0;
                        }
                }
        }
        double r6=0.0;
        double Am_int=Double.parseDouble(am_int.getText());
        double Am_term=Double.parseDouble(am_term.getText());
        double Am_sem=Double.parseDouble(am_sem.getText());
        if(Am_term>=10)
        {
                if(Am_int<8)
                {
                        if(Am_sem>=40)
                        {
                                r6=1.0;
                        }
                }
                else
                {
                        if(Am_sem>=24)
                        {
                                r6=1.0;
                        }
                }
        }
        R[0]=(4*(gp(Am_int+Am_sem)+gp(Edc_int+Edc_sem)+gp(Dcd_int+Dcd_sem)+gp(Enas_int+Enas_sem)+gp(Eim_int+Eim_sem))+gp(Am_term*4)+gp((Edc_pracs+Edc_term)*2)+gp((Dcd_pracs+Dcd_term)*2)+gp(Enas_term*4)+2*gp((Oopm_pracs+Oopm_term)*2))/26;
        if(r1==0.0||r2==0.0||r3==0.0||r4==0.0||r5==0.0||r6==0.0)
        {
                R[1]=0.0;
        }
        else
        {
                R[1]=1.0;
        }
        return R;
}

public double gp(double p)
{
        if(p>=80 && p<=100)
        {
                return 10.0;
        }
        else if(p>=75 && p<80)
        {
                return 9.0;
        }
        else if(p>=70 && p<75)
        {
                return 8.0;
        }
        else if(p>=60 && p<70)
        {
                return 7.0;
        }
        else if(p>=50 && p<60)
        {
                return 6.0;
        }
        else if(p>=45 && p<50)
        {
                return 5.0;
        }
        else if(p>=40 && p<45)
        {
                return 4.0;
        }
        else
        {
                return 0.0;
        }
}
private void dcd_intActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_dcd_intActionPerformed
        // TODO add your handling code here:
}    //GEN-LAST:event_dcd_intActionPerformed

private void eim_intActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_eim_intActionPerformed
        // TODO add your handling code here:
}    //GEN-LAST:event_eim_intActionPerformed

private void eim_semActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_eim_semActionPerformed
        // TODO add your handling code here:
}    //GEN-LAST:event_eim_semActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                break;
                        }
                }
        } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(cgpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(cgpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(cgpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(cgpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

                        public void run() {
                                new cgpi().setVisible(true);
                        }
                });
}
// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JTextField am_int;
private javax.swing.JTextField am_sem;
private javax.swing.JTextField am_term;
private javax.swing.JTextField dcd_int;
private javax.swing.JTextField dcd_pracs;
private javax.swing.JTextField dcd_sem;
private javax.swing.JTextField dcd_term;
private javax.swing.JTextField edc_int;
private javax.swing.JTextField edc_pracs;
private javax.swing.JTextField edc_sem;
private javax.swing.JTextField edc_term;
private javax.swing.JTextField eim_int;
private javax.swing.JTextField eim_sem;
private javax.swing.JTabbedPane eimpane;
private javax.swing.JTextField enas_int;
private javax.swing.JTextField enas_sem;
private javax.swing.JTextField enas_term;
private javax.swing.JLabel error_am;
private javax.swing.JLabel error_dcd;
private javax.swing.JLabel error_edc;
private javax.swing.JLabel error_eim;
private javax.swing.JLabel error_enas;
private javax.swing.JLabel error_oopm;
private javax.swing.JButton jButton1;
private javax.swing.JButton jButton2;
private javax.swing.JButton jButton3;
private javax.swing.JButton jButton4;
private javax.swing.JButton jButton5;
private javax.swing.JButton jButton6;
private javax.swing.JDialog jDialog1;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel10;
private javax.swing.JLabel jLabel11;
private javax.swing.JLabel jLabel12;
private javax.swing.JLabel jLabel13;
private javax.swing.JLabel jLabel14;
private javax.swing.JLabel jLabel15;
private javax.swing.JLabel jLabel16;
private javax.swing.JLabel jLabel17;
private javax.swing.JLabel jLabel18;
private javax.swing.JLabel jLabel19;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel20;
private javax.swing.JLabel jLabel21;
private javax.swing.JLabel jLabel22;
private javax.swing.JLabel jLabel23;
private javax.swing.JLabel jLabel24;
private javax.swing.JLabel jLabel25;
private javax.swing.JLabel jLabel26;
private javax.swing.JLabel jLabel27;
private javax.swing.JLabel jLabel28;
private javax.swing.JLabel jLabel29;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel30;
private javax.swing.JLabel jLabel31;
private javax.swing.JLabel jLabel32;
private javax.swing.JLabel jLabel33;
private javax.swing.JLabel jLabel34;
private javax.swing.JLabel jLabel35;
private javax.swing.JLabel jLabel36;
private javax.swing.JLabel jLabel37;
private javax.swing.JLabel jLabel38;
private javax.swing.JLabel jLabel39;
private javax.swing.JLabel jLabel4;
private javax.swing.JLabel jLabel40;
private javax.swing.JLabel jLabel41;
private javax.swing.JLabel jLabel42;
private javax.swing.JLabel jLabel43;
private javax.swing.JLabel jLabel44;
private javax.swing.JLabel jLabel46;
private javax.swing.JLabel jLabel47;
private javax.swing.JLabel jLabel48;
private javax.swing.JLabel jLabel49;
private javax.swing.JLabel jLabel5;
private javax.swing.JLabel jLabel50;
private javax.swing.JLabel jLabel6;
private javax.swing.JLabel jLabel7;
private javax.swing.JLabel jLabel8;
private javax.swing.JLabel jLabel9;
private javax.swing.JPanel jPanel1;
private javax.swing.JPanel jPanel2;
private javax.swing.JPanel jPanel3;
private javax.swing.JPanel jPanel4;
private javax.swing.JPanel jPanel5;
private javax.swing.JPanel jPanel6;
private javax.swing.JPopupMenu jPopupMenu1;
private javax.swing.JPopupMenu jPopupMenu2;
private javax.swing.JTextField oopm_pracs;
private javax.swing.JTextField oopm_term;
// End of variables declaration//GEN-END:variables
}
