/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cgpi;

/**
 *
 * @author student
 */
import java.util.*;
public class sign_up extends javax.swing.JFrame {

/**
 * Creates new form sign_up
 */
public sign_up() {
        initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

        fname = new javax.swing.JLabel();
        cpwd = new javax.swing.JLabel();
        rno = new javax.swing.JLabel();
        pwd = new javax.swing.JLabel();
        new_acc = new javax.swing.JButton();
        tpwd = new javax.swing.JPasswordField();
        tcpwd = new javax.swing.JPasswordField();
        tfname = new javax.swing.JTextField();
        trno = new javax.swing.JTextField();
        error = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" ACCOUNT PAGE");
        setBackground(new java.awt.Color(255, 255, 255));

        fname.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        fname.setText("FULL NAME");

        cpwd.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        cpwd.setText("CONFIRM PASSWORD");

        rno.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        rno.setText("ROLL NUMBER");

        pwd.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        pwd.setText("PASSWORD");

        new_acc.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        new_acc.setText("CREATE NEW ACCOUNT");
        new_acc.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                new_accActionPerformed(evt);
                        }
                });

        tfname.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tfnameActionPerformed(evt);
                        }
                });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("                  Registration Page");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Please enter numbers only.");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Please enter alphabets only.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                              .addGap(159, 159, 159)
                                              .addComponent(new_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                              .addGap(96, 96, 96)
                                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                      .addComponent(rno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                      .addComponent(cpwd)
                                                                                      .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                      .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                  .addGap(52, 52, 52)
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                            .addComponent(tpwd)
                                                                            .addComponent(tcpwd)
                                                                            .addComponent(tfname)
                                                                            .addComponent(trno, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jLabel6)
                                                        .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                          .addContainerGap(242, Short.MAX_VALUE))
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                          .addContainerGap()
                          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fname)
                                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel6)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rno)
                                    .addComponent(trno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jLabel5)
                          .addGap(18, 18, 18)
                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pwd)
                                    .addComponent(tpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addGap(28, 28, 28)
                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cpwd)
                                    .addComponent(tcpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                          .addGap(31, 31, 31)
                          .addComponent(new_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addContainerGap(53, Short.MAX_VALUE))
                );

        pack();
}    // </editor-fold>//GEN-END:initComponents

private void new_accActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_new_accActionPerformed
        String str=tfname.getText();
        char ch=' '; int flag=0;
        String sErr="Invalid entries in ";
        for(int i=0; i<str.length(); i++)
        {
                ch=str.charAt(i);
                if((ch<63&&ch>=0)&&(ch!=32))
                {
                        flag=1;
                        sErr=sErr+ "full name ";
                        break;
                }
                else{flag=0;}
        }

        if(!(Arrays.equals(tpwd.getPassword(),tcpwd.getPassword() )))
        {
                flag=1;
                sErr=sErr + "password and confirm password ";
        }
        try {
                int number = Integer.parseInt(trno.getText());
        } catch (NumberFormatException e) {
                flag=1;
                sErr=sErr + "roll number";
        }
        if(flag==1)
        {
                error.setText(sErr);
        }
        else
        {
                sign_in obj=new sign_in();
                obj.setVisible(true);
                this.setVisible(false);
        }
// TODO add your handling code here:
}    //GEN-LAST:event_new_accActionPerformed

private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
}    //GEN-LAST:event_tfnameActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                break;
                        }
                }
        } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

                        public void run() {
                                new sign_up().setVisible(true);
                        }
                });
}
// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JLabel cpwd;
private javax.swing.JLabel error;
private javax.swing.JLabel fname;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel5;
private javax.swing.JLabel jLabel6;
private javax.swing.JButton new_acc;
private javax.swing.JLabel pwd;
private javax.swing.JLabel rno;
private javax.swing.JPasswordField tcpwd;
private javax.swing.JTextField tfname;
private javax.swing.JPasswordField tpwd;
private javax.swing.JTextField trno;
// End of variables declaration//GEN-END:variables
}
